# Generated by Django 5.2.17 on 2026-09-02 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(default='', max_length=80)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_JORNADA', 'En Jornada'), ('COMPLETADO', 'Completado'), ('TARDANZA', 'Tardanza')], default='EN_JORNADA', max_length=12)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.empleado')),
            ],
            options={
                'db_table': 'registro_asistencia',
                'constraints': [models.UniqueConstraint(fields=('empleado', 'fecha'), name='una_entrada_por_jornada')],
            },
        ),
    ]
